---
Standards:
  # -
  #
  #   This Standard had one file, moved to the start of the next unit.
  #
  #   Title: Introduction
  #   UID: e4af066c-c195-484e-81af-ee21e50f9a5a
  #   Description: Context and reading for Module 1.
  #   SuccessCriteria:
  #     - Understand purpose of Module 1.
  #     # - (optional) Another success criteria, uncomment to use
  #   ContentFiles:
  #     -
  #       Type: Lesson
  #       UID: f528826d-7341-494e-b280-aba53f11f4f0
  #       Path: /reading/synopsis.md
  #     -
  #       Type: Checkpoint
  #       UID: 98853a0b-db1c-4548-a408-46124d2363b6
  #       Path: /reading/intro_checkpoint.md
  #       Autoscore: true

  #
  # RENAME objects to dictionaries to use with Python
  #
  #
  
  -
    Title: Part 1
    UID: 47567dbe-9f6a-451b-b52c-803b1ea45025
    Description: Solve Code Challenges
    SuccessCriteria:
      - Solve Python code challenges
      # - [(optional) Another success criteria, uncomment to use]
    ContentFiles:
      # -
      #   Type: Lesson
      #   UID: 9c7f3591-9dc7-4847-a833-9c6140e598ae
      #   Path: /reading/synopsis.md
      -
        Type: Lesson
        UID: bbd9c4ac-32ee-4474-b697-35173143e155
        Path: /challenges/conditionals1.md
      -
        Type: Lesson
        UID: 7de423a4-1fea-4226-b372-122d15e56d8a
        Path: /challenges/objects1.md
      -
        Type: Lesson
        UID: d77258c9-8844-4b41-a3fe-6cb0b7d1bd3d
        Path: /challenges/stringmethods1.md
      -
        Type: Lesson
        UID: b6bbe097-6367-4f7c-bee1-5adcf49ce589
        Path: /challenges/conditionals2.md
      -
        Type: Lesson
        UID: 419a2fd5-3863-4e7b-a799-dd13a168ddb1
        Path: /challenges/conditionals3.md
      -
        Type: Lesson
        UID: 5c19e93e-b90e-43b0-b1c4-b23c78976f2d
        Path: /challenges/conditionals4.md
      -
        Type: Lesson
        UID: 003da2a0-c949-4e03-b5e6-76753ea98c47
        Path: /challenges/conditionals5.md
      -
        Type: Lesson
        UID: 4ae664ad-7381-4190-83dd-581d43c6c6f5
        Path: /challenges/math1.md
      -
        Type: Lesson
        UID: affa07f6-d198-4723-8445-0ece8db5c8a3
        Path: /challenges/stringmethods2.md
        Autoscore: true
  -
    Title: Part 2
    UID: 9182cb5e-7e40-4e64-be22-e9ae72b69b01
    Description: Solve Code Challenges
    SuccessCriteria:
      - Solve JavaScript code challenges
      # - (optional) Another success criteria, uncomment to use
    ContentFiles:
      # -
      #   Type: Lesson
      #   UID: unique-id (option-command-G from uuidgen plugin)
      #   Path: /folder/file.md
      -
        Type: Lesson
        UID: a0f63947-9772-4f4d-9b87-a9d536f053ef
        Path: /challenges/objects2.md
      -
        Type: Lesson
        UID: db0c1ec1-ed3a-4737-9d1e-b54e19bebbb5
        Path: /challenges/objects3.md
      -
        Type: Lesson
        UID: acdab971-cf11-4bf3-8459-43295a24f974
        Path: /challenges/arraymethods1.md
      -
        Type: Lesson
        UID: e4516013-fec9-4863-9c96-a7ff9568b920
        Path: /challenges/arraymethods2.md
      -
        Type: Lesson
        UID: cd7b33f1-d189-4445-8b87-3fd3e1860402
        Path: /challenges/math2.md
      -
        Type: Lesson
        UID: 549587b6-2fd4-44d7-9492-fc2b87e2c18f
        Path: /challenges/math3.md
      -
        Type: Lesson
        UID: 26313a8a-8ae9-420a-b687-2da79f145ebe
        Path: /challenges/math4.md
      -
        Type: Lesson
        UID: a5307160-3fcc-4685-9119-40039900d9bc
        Path: /challenges/stringmethods3.md
      -
        Type: Lesson
        UID: 9f07d18a-55cc-4fa7-b849-160f9ecb3317
        Path: /challenges/arraymethods3.md
      -
        Type: Lesson
        UID: 1bd2583e-24c8-477c-873c-5e0288e13651
        Path: /challenges/arraymethods4.md
      -
        Type: Lesson
        UID: 0ba0c75b-e834-41f5-98e4-784e68d35e5d
        Path: /challenges/arraymethods5.md
        Autoscore: true
  -
    Title: Part 3
    UID: 2c549be4-cd7a-4e99-8010-4eea8c094d98
    Description: Solve Code Challenges
    SuccessCriteria:
      - Solve JavaScript code challenges
      # - (optional) Another success criteria, uncomment to use
    ContentFiles:
      -
        Type: Lesson
        UID: 50d6e1e9-06fa-4de9-92e3-578b36fda7e3
        Path: /challenges/arraystringmethods1.md
      -
        Type: Lesson
        UID: 1ac724b0-ffee-4edb-a144-41cab357c290
        Path: /challenges/advanced1.md
      -
        Type: Lesson
        UID: e5533c1b-f3a1-4b25-a479-deb411b09c46
        Path: /challenges/arraymethods6.md
      -
        Type: Lesson
        UID: 66c67021-10ef-419f-b4d3-1da3256b1451
        Path: /challenges/conditionals6.md
      -
        Type: Lesson
        UID: d487113b-5cdc-4ac3-a7ba-afb7a67c5103
        Path: /challenges/advanced2.md
      -
        Type: Lesson
        UID: 3f7e5bdb-682c-4f15-ae40-1a4375ce704b
        Path: /challenges/objects4.md
      -
        Type: Lesson
        UID: 9f42274b-390b-44cd-914e-fb0d5b1fda43
        Path: /challenges/objects5.md
      -
        Type: Lesson
        UID: bfadcea2-bb6b-4606-b88c-c9a97ea6dfa6
        Path: /challenges/objects6.md
      -
        Type: Lesson
        UID: 23e7cb41-ba68-4143-bcf2-96cbca222337
        Path: /challenges/arraystringmethods2.md
      -
        Type: Lesson
        UID: cf71f041-2465-48d1-9332-7b3b0f64b200
        Path: /challenges/arraymethods7.md
      -
        Type: Lesson
        UID: ada4947d-6eb6-4621-987c-7f50f36ab0fa
        Path: /challenges/iteration1.md
      -
        Type: Lesson
        UID: 1b82dcba-4552-403a-828b-5821a268880e
        Path: /challenges/conditionals7.md
      -
        Type: Lesson
        UID: 4401d6c4-5b17-4e89-98b1-ccd746e95814
        Path: /challenges/advanced3.md
        Autoscore: true
  -
    Title: Part 4
    UID: 29e76b90-d7ce-4541-9706-bf73cc7a2178
    Description: Solve Code Challenges
    SuccessCriteria:
      - Solve JavaScript code challenges
      # - (optional) Another success criteria, uncomment to use
    ContentFiles:
      -
        Type: Lesson
        UID: 9a85983f-85e6-4f3f-b49c-5ff9a31001da
        Path: /challenges/objects7.md
      -
        Type: Lesson
        UID: e241db10-4f97-4830-9ccb-69f57ceb95ab
        Path: /challenges/advanced4.md
      -
        Type: Lesson
        UID: 64f2ceb0-0663-4661-a443-f2036f8a253a
        Path: /challenges/objects8.md
      -
        Type: Lesson
        UID: 0972add3-be30-4c1a-a58d-be8d6b2be8de
        Path: /challenges/arraymethods8.md
      -
        Type: Lesson
        UID: 238aa790-a77d-4e4a-9301-d99fc8df0f7d
        Path: /challenges/objects9.md
      -
        Type: Lesson
        UID: fe48230b-c02f-4b37-8dae-1468b08a4bde
        Path: /challenges/objects10.md
      -
        Type: Lesson
        UID: 0433a235-634c-41dc-b36b-23b7bdaed6b6
        Path: /challenges/arraymethods9.md
      -
        Type: Lesson
        UID: 7f8ba3bf-11da-47b3-ab3a-4e8f24af2e2c
        Path: /challenges/objects11.md
      -
        Type: Lesson
        UID: ba5bec61-dcde-4db6-9490-9cf3ba789d0a
        Path: /challenges/arraymethods10.md
      -
        Type: Lesson
        UID: 3b4790ef-6ddd-46eb-ae5a-3a08baa4ee60
        Path: /challenges/arraymethods11.md
        Autoscore: true
  -
    Title: Part 5
    UID: aa8fbca0-be5e-418c-8165-ae834b79d225
    Description: Solve Code Challenges
    SuccessCriteria:
      - Solve JavaScript code challenges
      # - (optional) Another success criteria, uncomment to use
    ContentFiles:
      -
        Type: Lesson
        UID: 9fd7cf80-e499-4cf2-af03-295843af34a8
        Path: /challenges/arraymethods12.md
      -
        Type: Lesson
        UID: 5f2620de-7929-4fed-9e5f-fa759e5d6e24
        Path: /challenges/arraymethods13.md
      -
        Type: Lesson
        UID: 24568ce9-71d9-4f2a-b0fc-41d8c6e6e1cf
        Path: /challenges/math5.md
      -
        Type: Lesson
        UID: 4fcfebe1-19a6-4d67-9af9-bf40ecbb6873
        Path: /challenges/iteration2.md
      -
        Type: Lesson
        UID: d5c3c5fc-e07f-49bf-a489-bb0c504c5f1e
        Path: /challenges/arraymethods14.md
      -
        Type: Lesson
        UID: 43db9031-9a69-4e2c-a96c-9476aca5bf86
        Path: /challenges/objects12.md
      -
        Type: Lesson
        UID: 4c768066-f29e-4a9c-a6fd-4f69946a6689
        Path: /challenges/advanced5.md
      -
        Type: Lesson
        UID: 4a0d7237-1f0f-4210-b040-d5ee847b0ef5
        Path: /challenges/objects13.md
      -
        Type: Lesson
        UID: d477bfb0-4cd0-487f-bb94-58095f831dfe
        Path: /challenges/arraymethods15.md
      -
        Type: Lesson
        UID: 8cbd5ead-0d7e-46e2-8fbb-45c61dc17c65
        Path: /challenges/arraymethods16.md
      -
        Type: Lesson
        UID: 6cc90df0-1b85-45f6-9f4f-e884e96335e9
        Path: /challenges/iteration3.md
      -
        Type: Lesson
        UID: 3cfbf2f2-f1bc-4d24-b3f0-8d7f104cd21e
        Path: /challenges/conditionals8.md
      -
        Type: Lesson
        UID: d8b2743f-4265-4448-a042-ef2861f3dbd6
        Path: /challenges/iteration4.md
      -
        Type: Lesson
        UID: 3ff902b3-0b98-415b-a661-62a18c8ecc1f
        Path: /challenges/conditionals9.md
      -
        Type: Lesson
        UID: 1129dedb-e249-4a88-a58a-f6ce767f7e8f
        Path: /challenges/math6.md
      -
        Type: Lesson
        UID: b3ccfc3c-42b6-41e7-ac44-a36ec8dc1f26
        Path: /challenges/advanced6.md
      -
        Type: Lesson
        UID: 4d73d780-0ea3-43c4-b40f-c68e8bb2853e
        Path: /challenges/iteration5.md
      -
        Type: Lesson
        UID: 30123aae-8a66-44c7-9de1-c0825a512390
        Path: /challenges/advanced7.md
      -
        Type: Lesson
        UID: 753e083f-ba49-4a5d-856b-944f1fd7f5ff
        Path: /challenges/advanced8.md
      -
        Type: Lesson
        UID: 5a87c6d1-291e-4987-9318-f773cb649764
        Path: /challenges/iteration6.md
        Autoscore: true
  -
    Title: Diagnostic Skills Check
    UID: cf43a521-59b3-4059-bd4c-53346c76007f
    Description: A cumulative set of exercises ranging over topics featured Module 1. The ability to complete these problems indicates that you are likely ready for Module 2.
    SuccessCriteria:
      - Complete these cumulative exercises.
      - Verify that you are ready to move on to Module 2.
    ContentFiles:
      -
        Type: Lesson
        UID: 469e8b2a-c403-4f7e-b2fd-2357523d16d1
        Path: /diagnostic/146-convertArrayToObject1.md
      -
        Type: Lesson
        UID: c3bd9a0a-c98b-4ef0-bbd9-377dcd632800
        Path: /diagnostic/147-convertArrayToObject2.md
      -
        Type: Lesson
        UID: 882d1b16-6e23-4f10-b385-06a0b13ae65e
        Path: /diagnostic/148-convertArrayToObject3.md
      -
        Type: Lesson
        UID: ce7a6f05-9558-485b-858f-aebac959f6d6
        Path: /diagnostic/149-convertObjectToList1.md
      -
        Type: Lesson
        UID: fc319ecb-3275-48ad-bca6-b13f5311d057
        Path: /diagnostic/150-convertObjectToList2.md
      -
        Type: Lesson
        UID: 3f2e29ad-4332-4158-8cb2-f9ef1385d2e4
        Path: /diagnostic/151-convertObjectToList3.md
      -
        Type: Lesson
        UID: unique-id (option-command-G from uuidgen plugin)
        Path: /diagnostic/152-greetCustomer.md
        Autoscore: true
